### Programming Assignment 2 - NUMBER PYTHON (NUMPY)
#### By: CASTILLO, Aurabella Macy F.
#### Section: 2ECE-C

In [20]:
import numpy as np

##### **PROBLEM 1** - NORMALIZATION PROBLEM: Normalization is one of the most basic preprocessing techniques in data analytics. This involves centering and scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation. Save your normalized ndarray as X_normalized.npyy 

In [26]:
#Normalization Function
X=np.random.random((5,5))
normalized_X=((X-np.mean(X))/np.std(X))

#Print Original Array
print("Original Array:")
print(X)

#Print Normalized Array
print("\nNormalized Array:")
print(normalized_X)

#Save Normalized Array as ndarray
np.save('X_normalized.npy', normalized_X)

Original Array:
[[0.73212288 0.83059506 0.82179536 0.22573159 0.73346662]
 [0.26768862 0.45944733 0.21201316 0.5753728  0.2948235 ]
 [0.16134566 0.06441868 0.85519033 0.50966471 0.00285477]
 [0.96429818 0.79151665 0.7763656  0.17511806 0.27445371]
 [0.9653774  0.70703702 0.9704637  0.04447164 0.64691151]]

Normalized Array:
[[ 0.66405407  0.97600195  0.94812557 -0.94013179  0.66831089]
 [-0.80721703 -0.19974882 -0.98359009  0.16748895 -0.72125704]
 [-1.14409854 -1.45115139  1.05391674 -0.04066628 -1.64617837]
 [ 1.39955712  0.8522063   0.80420963 -1.10046928 -0.78578606]
 [ 1.40297596  0.58458512  1.41908874 -1.51434119  0.39411484]]


##### **PROBLEM 2** - DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray. which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [44]:
#Generate an array of the first 100 integers
integer = np.arange(1, 101)

#Square each element in the array
squares = integer ** 2

#Reshape the array to a 10x10 matrix
A = squares.reshape(10, 10)

#Indice Function to find every squared integer divisible by 3
indices = np.where(A % 3 == 0)

# Extract the elements divisible by 3
divisible_by_3 = A[indices]

#Print Squares of First 100 Positive Integers Array
print("\nSquares of First 100 Positive Integers Array:")
print(A)

#Print Squares of First 100 Positive Integers that is Divisible by 3 Array
print("\nSquares of First 100 Positive Integers that is Divisible by 3 Array:")
print(divisible_by_3)

#Save the divisible_by_3 array to a .npy file
np.save("div_by_3.npy", divisible_by_3)


Squares of First 100 Positive Integers Array:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Squares of First 100 Positive Integers that is Divisible by 3 Array:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
